apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: spring-sensors
  labels:
    apps.tanzu.vmware.com/workload-type: server
    se.tanzu.vmware.com/edge: "true"
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: edge-relocate
spec:
  source:
    image: harbor.workshop.amer.end2end.link/tap/supply-chain/spring-sensors-edge-bundle@sha256:5313898a5c5a592c964ad8edf7e77ec106f995d45c18e83490b218bf3640b360

